### ISSUE TITLE
Replace forbidden characters in publicId

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#121]
https://github.com/LaunchPadLab/lp-hoc/blob/882c9358380cb45cbabb34a9f541beae5400640d/src/cloudinaryUploader.js#L78

Should we allow an invalid file name to be passed in or should we automatically replace invalid characters? We could try leveraging `encodeURIComponent` or replace the "forbidden" characters outright?

https://support.cloudinary.com/hc/en-us/articles/115001317409--Legal-naming-conventions

**Comment by dpikt** [comment]
@chawes13 this is a good enhancement. I don't know a ton about percent encoding but if it works for this purpose it'd be nice to leverage `encodeURIComponent`.
