### ISSUE TITLE
Cloudinary doesn't accept single html escaped characters

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#123]
This could potentially be a defect on their end, but for the time being [release v4.5.6](https://github.com/LaunchPadLab/lp-hoc/releases/tag/v4.5.6)  does not upload files with invalid characters correctly. I'll resolve this by implementing the fix(es) suggested by Cloudinary Support or by reverting the last release (depending on the suggestions).

**Comment by chawes13** [comment]
cc: @dpikt At the very least I'll revert by EOW to minimize the download #s for the latest release

**Comment by dpikt** [comment]
@chawes13 gotcha, sounds good. Not a big rush since invalid file names are already broken in prior releases!
