### ISSUE TITLE
Archived recompose dependency affecting the security vulnerabilities report for Snyk

### ISSUE THREAD

**Issue by aalejandromr** [LaunchPadLab/lp-hoc#164]
It seems like the `recompose` library we use to display the name of the HOC is not being maintained anymore and since it's a dependency of this repository it's affecting the security vulnerabilities report for Prosci.

Snyk is finding a [Denial of Service](https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-674311) vulnerability, because the node-fetch package version recompose, is using.

To my understanding we should not be using the part of the code that has the vulnerability because we are only using the `wrapDisplayName` function from recompose but I think is worth finding a replacement for the function we use knowing that the package is not going to be maintained anymore.

From the author of the recompose package:

> Hooks solves all the problems I attempted to address with Recompose three years ago, and more on top of that. I will be discontinuing active maintenance of this package

We should explore which function could replace the `wrapDisplayName` function, or even mimic that function in a util ourselves. From what I can see in the codebase should be pretty straightforward.

If this sounds good I can assign this issue to myself.

Edit: Adding this report too https://security.snyk.io/vuln/SNYK-JS-NODEFETCH-2342118

**Comment by chawes13** [comment]
Yes, I've run into this issue recently as well. Out of curiosity, is the application that you're working on using `lp-hoc` extensively? For all intents and purposes this repo is archived and is no longer used in our modern day React applications.

What would the effort be to migrate _away_ from `lp-hoc` entirely versus updating this package with a local `wrapDisplayName` util?

**Comment by aalejandromr** [comment]
@chawes13 Good call.

I think we only use it in our prosci-components library to wrap the elements in a default class using `withClassName('content-card')('div')`

Migrating away from this repo should be a low lift and low impact.  I'll let the Prosci team know we will migrate away from lp-hoc repo altogether.

Thanks!
