### ISSUE TITLE
Add `updateDocumentTitle` HOC

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-hoc#21]
From artlook, once it's needed on a new project.

**Comment by dpikt** [comment]
We might want to use this next time instead (Dan Abramov wrote it):
https://github.com/gaearon/react-document-title

**Comment by rkillackey** [comment]
Not as prestigious as "Rachel Killackey wrote it" or "David Pickart wrote it" tbh... 😄

**Comment by dpikt** [comment]
@rkillackey one day 🙌
