### ISSUE TITLE
Remove default loading indicator for `waitFor`

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-hoc#3]
Or at least create a better one.

**Comment by rkillackey** [comment]
@dpikt Thoughts on using the `LoadingSpinner` from `lp-components` by default instead?

**Comment by dpikt** [comment]
I think that'd be fine, my only concern is adding the dependency. But since we always use them in tandem anyway... ¯\_(ツ)_/¯

We also need to make it easy to hide the spinner (maybe just a falsey check on the second arg?)

**Comment by rkillackey** [comment]
@dpikt I think it would have to be a strictly `false` check, no? Otherwise it doesn't seem like it would be possible to set the `DefaultLoadingComponent` if the second arg was `undefined` or `null`

**Comment by dpikt** [comment]
@rkillackey yeah we definitely have to watch out for `undefined`. It's up to you whether you wan to allow `null`.
