### ISSUE TITLE
Add onUpdate HOC that just watches certain keys

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-hoc#45]

**Comment by rkillackey** [comment]
💯 🎉 👍

**Comment by dpikt** [comment]
This could be accomplished by passing an option:

```
onUpdate(doStuffWhenParamsChange, { on: 'params' }) 
```

@rkillackey @chawes13 thoughts?

**Comment by rkillackey** [comment]
Any downsides of just passing in an array of strings as the second arg?

**Comment by dpikt** [comment]
@rkillackey it would make it harder to add other options in the future if we wanted them. However we could definitely allow an array argument for `on` or call it something else like `watch`, `keys` etc

**Comment by dpikt** [comment]
Closed in favor of https://reactjs.org/docs/hooks-effect.html
