### ISSUE TITLE
Prevent background scrolling when modal is open

### ISSUE THREAD

**Issue by rkillackey** [LaunchPadLab/lp-hoc#47]

**Comment by rkillackey** [comment]
Maybe this is something we can accomplish with css?

**Comment by dpikt** [comment]
@victoriapalacios you've been looking at modal styles recently, thoughts?

**Comment by rkillackey** [comment]
Gotcha. Just tried this out in the Omaha repo, and the issue is that `modal` won't always be a direct child of `body`, it's often nested within a bunch of divs

**Comment by rkillackey** [comment]
@victoriapalacios ^ Would there be another way to target the `body` if the `modal` class is present?

**Comment by victoriapalacios** [comment]
@rkillackey So what you could do is add a class to `<body>` when the modal is active.

in `index.html` it would look like this: `<body class="noScroll">`

and the css would be:

```
body.noScroll {
  overflow: hidden;
}
```

The noScroll class would be removed once you close the modal.

**Comment by dpikt** [comment]
@rkillackey Looks like modifying the body tag is really the only way to do this:

https://davidwalsh.name/prevent-body-scrolling (see comments)

Looks like https://github.com/iest/react-body-classname can help us.

On a tangent, I also just found this 😀https://github.com/gaearon/react-document-title
