### ISSUE TITLE
Add redirectUnless

### ISSUE THREAD

**Issue by dpikt** [LaunchPadLab/lp-hoc#62]
From cpp & apex

**Comment by dpikt** [comment]
And ignore self-redirects

**Comment by dpikt** [comment]
And allow string args

**Comment by dpikt** [comment]
This has been kicking around for a while. @chawes13 @bhennes2 how do you feel about this HOC as it's appeared in your projects? Is the syntax confusing? (`redirectUnless` vs `redirectIf`).

One enhancement I'd like to make is to run the check just once on mount. However, this might be breaking from the it's currently being used.

**Comment by dpikt** [comment]
This is less relevant in a hook-based world. @chawes13 would you still prefer this to be in the library or is it not worth the lift?

**Comment by chawes13** [comment]
Not worth it!
