### ISSUE TITLE
Allow custom loading messages in waitFor

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#68]
Passing in a string for the second argument should replace text rendered in paragraph tags.

e.g., waitFor('memberships', 'Fetching profile...')

**Comment by chawes13** [comment]
^ this is an idea

**Comment by rkillackey** [comment]
You should be able to pass in a custom component to `waitFor`!

e.g.,

```
waitFor('memberships', LoadingComponent)

const LoadingComponent = () => <p>Fetching Profile...</p>
```

**Comment by dpikt** [comment]
This is a good idea but will no longer be relevant in v2, we're replacing the p tag loader with a spinner (see https://github.com/LaunchPadLab/lp-hoc/issues/3). If you find yourself using text loading indicators a lot we could still add this functionality but I think it might be a little obscure. 

Speaking of v2, we should probably merge that in, it looks like there are no outstanding issues.

**Comment by dpikt** [comment]
Also fun fact the way it's built now does accept string arguments- `a`, `b`, and `i` for example 😁

**Comment by chawes13** [comment]
Ok, no worries. Should I mark this as closed?

**Comment by dpikt** [comment]
Yes please!
