### ISSUE TITLE
Modal throws synthetic event warnings

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#72]
A quick fix for this is to wrap the function in mapDispatchToProps in an anonymous function. Further investigation may be required to understand the "props" arguments that is expected and what the impact is of passing in undefined instead of the event from the onClick handler.

**Comment by dpikt** [comment]
A less-quick fix would be to wrap `show/hide` in a function that ignores event arguments. Or, if we don't ignore it those arguments, at least throw an exception or log a warning that's less opaque than the current one.

@chawes13 thoughts?

**Comment by chawes13** [comment]
@dpikt Can you think of a valid use case where ignoring the event would be an issue? I'm leaning towards the former

**Comment by dpikt** [comment]
@chawes13 I don't think it would be, but it's important to think about how we check to see what's an event and what's not. We don't want to ignore a valid props object by accident. For instance, using the first answer [here](https://stackoverflow.com/questions/1458894/how-to-determine-if-javascript-object-is-an-event) we would unwittingly ignore an object that includes a `target` prop (a little contrived but possible).

Unfortunately, there isn't a single unified way to check whether an event is an object in JS. So we just need to settle on a method that we feel is robust enough.

**Comment by dpikt** [comment]
Apparently this isn't happening in `2.8.1`... could be due to a patch in `redux-modal`? Quick fix is to upgrade to that version.

**Comment by chawes13** [comment]
@dpikt - Turns out I was very wrong. The event is still thrown with the newer version, not sure why I thought I had a false positive last night... 🙈

**Comment by dpikt** [comment]
Blast !
