### ISSUE TITLE
A11y Modal Enhancements

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#82]
Escape should close modal

https://www.w3.org/TR/wai-aria-practices/#dialog_modal

**Comment by chawes13** [comment]
From ARIA practices:
1. When a dialog opens, focus placement depends on the nature and size of the content.
    - In all circumstances, focus moves to an element contained in the dialog.
    - Unless a condition where doing otherwise is advisable, focus is initially set on the first focusable element.
2. When a dialog closes, focus returns to the element that invoked the dialog.

@dpikt thoughts on how to move focus back to the invoking element?

**Comment by dpikt** [comment]
@chawes13 hmm that's an interesting idea. It would require a bit of setting up but I think this would work:

```js
<button onClick={ (e) => showModal({ invoker: e.target }) }> Show </button>
// in modal
<button onClick={ () => { 
   handleHide()
   invoker.focus()
}}
```
The only library change I can think of that would make this easier would be to automatically call this focus function when the invoking element is set, but that would require us either to add another argument to `show` for that element or use a special prop name. Either way it requires some extra setup when the modal is shown.

**Comment by chawes13** [comment]
@dpikt We need to do the following:
1. Trap focus (Reach uses https://www.npmjs.com/package/react-focus-lock)
2. Disable scroll (I think we've already accomplished this)
3. Add aria-hidden attributes to all external nodes (https://github.com/theKashey/aria-hidden could potentially be used or we could roll our own)

**Comment by dpikt** [comment]
@chawes13 how do you feel about https://github.com/reactjs/react-modal? Is it something we could slot in under the hood?

**Comment by dpikt** [comment]
@chawes13 how has `react-modal` been treating you on artlook?

**Comment by chawes13** [comment]
@dpikt Really good! I'm in favor of pulling that change in

**Comment by dpikt** [comment]
👍
