### ISSUE TITLE
Pass option to waitFor to render "invisible" children to preserve DOM spacing/order

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-hoc#97]
Example use case: waiting for API action to retrieve certain details of a component that is nested within a layout that has dependent column spacing (Retrieving ticket details but still displaying receipt)

https://cl.ly/0a3b2692e94c

**Comment by dpikt** [comment]
As per our discussion, we can accomplish this via some changes to the `LoadingComponent` argument. Here's a loading component that will take up the same space as the view by "invisibly" rendering it:
```
const Hidden = props => <div style={{ visibility: 'hidden' }} { ...props }/>
const LoadingComponent = () => <><Spinner /><Hidden><MyView /></Hidden></>

export default compose(
    waitFor('condition', LoadingComponent)
)(MyView)
```
